This short introduction uses Keras to:

1. Load a prebuilt dataset.
2. Build a neural network machine learning model that classifies images.
3. Train this neural network.
4. Evaluate the accuracy of the model.

In [1]:
import tensorflow as tf
print('Tensorflow version : ',tf.__version__)

Tensorflow version :  2.15.0


## Load a dataset
Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255. Scale these values to a range of 0 to 1 by dividing the values by 255.0. This also converts the sample data from integers to floating-point numbers:


The dataset is divided into two parts: the training set and the test set.
1. x_train and y_train are the training data and labels.
2. x_test and y_test are the test data and labels.

In [2]:
mnsit = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnsit.load_data()
x_train = x_train / 255.0
x_test = x_test / 255.0
x_train

11490434/11490434 [==============================] - 0s 0us/step


array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [3]:
model  = tf.keras.models.Sequential([
    #The Flatten layer converts each 28x28 image into a 1D array of 784 elements (28*28).
    tf.keras.layers.Flatten(input_shape=(28,28)),
    #The Dense layer is a fully connected layer with 128 neurons.
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101770 (397.54 KB)
Trainable params: 101770 (397.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


For each example, the model returns a vector of logits or log-odds scores, one for each class.

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.28038394, -0.05377664,  0.4020189 ,  0.2976124 ,  0.35729736,
         0.08972459,  0.03806289,  0.54428136,  0.38823605, -0.5405056 ]],
      dtype=float32)

The tf.nn.softmax function converts these logits to probabilities for each class:

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.10627283, 0.07608484, 0.12001835, 0.1081196 , 0.11476918,
        0.08782535, 0.08340336, 0.13836664, 0.1183755 , 0.0467643 ]],
      dtype=float32)

# Now define a loss function
The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example. This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

In [6]:
loss_function = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.

In [7]:
loss_function(y_train[:1],predictions).numpy()

2.432405

Before you start training, configure and compile the model using Keras Model.compile. Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [8]:
model.compile(
    optimizer ='adam',
    loss = loss_function,
    metrics = [
        'accuracy',
       # tf.keras.metrics.Precision(name='precision'),
       # tf.keras.metrics.Recall(name='recall'),
        ]
)

Train and Evalutation

In [9]:
model.fit(x_train,y_train,epochs=5,)

Epoch 1/5
1875/1875 [==============================] - 8s 3ms/step - loss: 0.2983 - accuracy: 0.9132
Epoch 2/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.1458 - accuracy: 0.9567
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1097 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0893 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0747 - accuracy: 0.9769


In [10]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0786 - accuracy: 0.9757 - 777ms/epoch - 2ms/step


[0.07862527668476105, 0.9757000207901001]